### ISSUE TITLE
Add whitelisted pubkeys support to write events

### ISSUE THREAD

**Issue by atrifat** [imksoo/nostr-filter#1]
Sometimes, relay operator want to limit their user only to selected whitelisted pubkey. Any other events outside of whitelisted pubkeys should be rejected. This will be helpful especially for relay implementation which doesn't have built-in whitelist features. nostr-filter can act as proxy in the front of those relay.

**Comment by imksoo** [comment]
Thank you for getting in touch. I wholeheartedly agree with your proposal. Especially the idea of using the nostr-filter as a frontend proxy in the implementation of a relay that does not have whitelist functionality is extremely helpful. I am sincerely grateful for the time and effort you have spent on this issue.

Your pull request is warmly welcomed by us, and we would like to merge it. Thank you.

**Comment by atrifat** [comment]
Thank you imksoo-san, thank you for nostr-filter. nostr-filter has been pretty useful especially for my personal custom relay project. :)
