### ISSUE TITLE
Add production node env support

### ISSUE THREAD

**Issue by atrifat** [imksoo/nostr-filter#6]
imksoo-san, i have seen some cases whenever nostr-filter log a lot messages (console.log) the performance of nostr-filter will be slower. In my case, i found that by limiting/suppressing in "production" environment can help solve this issue.

I will send the PR later. Thank you.

**Comment by imksoo** [comment]
Hi, Thank you PR. I've marged.

**Comment by atrifat** [comment]
Thank you, imksoo-san.
